=== AndreiIonica/fake_news/backend/src/api/0.1/news/news.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "title": "User",
  "description": "The user object schema.No required properties as we dont create users here.",
  "default": {},
  "required": [],
  "additionalProperties": false,
  "properties": {
    "id": {
      "$id": "#/properties/id",
      "type": "integer",
      "title": "The database id"
    },
    "link": {
      "$id": "#/properties/link",
      "type": "string",
      "title": "Link of the article."
    },
    "title": {
      "$id": "#/properties/title",
      "type": "string",
      "title": "The title of the post."
    },
    "correction": {
      "$id": "#/properties/correction",
      "type": "string",
      "title": "The correction string of the post."
    },
    "type_id": {
      "$id": "#/properties/type_id",
      "type": "number",
      "title": "The type_id "
    },
    "user_id": {
      "$id": "#/properties/user_id",
      "type": "number",
      "title": "The user_id "
    },
    "created_at": {
      "$id": "#/properties/created_at",
      "type": "string",
      "title": "The date the trashcan_type was created"
    },
    "update_at": {
      "$id": "#/properties/updated_at",
      "type": "string",
      "title": "The date the trashcan_type was last updated"
    },
    "deleted_at": {
      "$id": "#/properties/deleted_at",
      "type": "string",
      "title": "The date the trashcan_type was deleted"
    }
  }
}

=== AndreiIonica/fake_news/backend/db/sources/news.json
[
    {
    "link": "http://argumentul.ro/single.php?id=367",
    "title": "A murit Ion Iliescu",
    "correction": "Ion Iliescu nu a murit",
    "type_id": 1,
    "user_id": 1
},
{
    "link": "https://www.timesnewroman.ro/life-death/un-rus-a-dat-mingea-peste-gard-pana-in-ucraina-40-000-de-soldati-trimisi-dupa-ea/",
    "title": "Un rus a dat mingea peste gard pana in Ucraina.40000 de soldati trimisi dupa ea",
    "correction": "",
    "type_id": 4,
    "user_id": 1
},
{
    "link": "https://m.monitorulsv.ro/Local/2020-03-31/Nas-de-tren-internat-la-Boli-Infectioase-cu-suspiciune-de-coronavirus",
    "title": "Nas de tren internat la Boli Infectioase cu suspiciune de coronavirus",
    "correction": "https://www.cfrcalatori.ro/fake-news/stire-falsa/",
    "type_id": 5,
    "user_id": 1
},
{
    "link": "https://josbotnita.ro/vaccin-coronavirus-janssen-tromboze-deces-stare-grava/?fbclid=IwAR2gMSTA6nPxP0Xar7hdq03D0PIMrlSqDhAqqJWmcKn94Igl0hon0f7jFmE",
    "title": "SUA recomandă oprirea vaccinării cu vaccinul Janssen după ce mai multe persoane sunt in stare grava si alta a murit",
    "correction": "În acest moment, nu am găsit o legătură cauzală cu vaccinarea şi continuăm investigaţia şi evaluarea acestor cazuri,a dat asigurări FDA",
    "type_id": 4,
    "user_id": 1
},
{
    "link": "https://josbotnita.ro/mastile-faciale-contin-substante-toxice-cauzatoare-de-cancer/",
    "title": "Măștile faciale conțin substanțe toxice cauzatoare de cancer",
    "correction": "Măștile faciale nu conțin substanțe toxice cauzatoare de cancer",
    "type_id": 5,
    "user_id": 1
},
{
    "link": "https://www.digi24.ro/stiri/actualitate/politica/ludovic-orban-orice-ministru-trebuie-sa-stie-ca-daca-isi-ataca-premierul-trebuie-sa-aiba-bagajele-facute-si-demisia-scrisa-1498871",
    "title": "Ludovic Orban: Orice ministru trebuie să știe că dacă își atacă premierul trebuie să aibă bagajele făcute și demisia scrisă",
    "correction": "",
    "type_id": 1,
    "user_id": 1
},
{
    "link": "https://www.mediafax.ro/politic/cimpeanu-explica-rezultatele-la-simularea-evaluarii-nationale-criza-scoate-ce-i-mai-bun-din-elevi-20045334",
    "title": "Cîmpeanu explică rezultatele la simularea Evaluării Naţionale: Criza scoate ce-i mai bun din elevi",
    "correction": "",
    "type_id": 1,
    "user_id": 1
},
{
    "link": "https://m.hotnews.ro/stire/24741634",
    "title": "Ministrul Muncii, Raluca Turcan, spune că angajații caselor de pensii care lucrează la recalcularea dosarelor de pensii vor primi stimulente, această activitate urmând să fie accelerată și cu suplimentări temporare de personal.",
    "correction": "",
    "type_id": 1,
    "user_id": 1
},
{
    "link": "https://www.realitatea.net/stiri/actual/ludovic-orban-nu-exista-alta-formula-de-guvernare-in-afara-coalitiei-le-recomand-celor-din-usrplus-sa-faca-o-analiza-obiectiva-in-cazul-lui-vlad-voiculescu_607ac4e490f5cd4c7f1c2132",
    "title": "Ludovic Orban: „Nu există altă formulă de guvernare în afara Coaliției. Le recomand celor din USR-PLUS să facă o analiză obiectivă în cazul lui Vlad Voiculescu”",
    "correction": "",
    "type_id": 1,
    "user_id": 1
},
{
    "link": "https://www.b1.ro/stiri/eveniment/ludovic-orban-ministrul-care-ataca-premierul-sa-si-scrie-demisia-365561.html",
    "title": "Ludovic Orban: Ministrul care atacă premierul, să-și scrie demisia",
    "correction": "",
    "type_id": 1,
    "user_id": 1
},
{
    "link": "https://www.digi24.ro/stiri/externe/rusia-trimite-15-nave-militare-in-marea-neagra-pentru-manevre-militare-1498915",
    "title": "Rusia trimite 15 nave militare în Marea Neagră pentru manevre militare",
    "correction": "",
    "type_id": 4,
    "user_id": 1
},
{
    "link": "https://www.digi24.ro/stiri/externe/serviciul-rus-de-securitate-fsb-a-retinut-pentru-cateva-ore-un-diplomat-ucrainean-1498849",
    "title": "Serviciul rus de securitate FSB a reţinut pentru câteva ore un diplomat ucrainean",
    "correction": "",
    "type_id": 4,
    "user_id": 1
},
{
    "link": "https://www.b1.ro/stiri/externe/trei-astronauti-s-au-intors-din-misiunea-de-pe-statia-spatiala-internationala-365556.html",
    "title": "Trei astronauţi s-au întors din misiunea de pe Staţia Spaţială Internaţională",
    "correction": "",
    "type_id": 4,
    "user_id": 1
},
{
    "link": "https://adevarul.ro/international/europa/austria-treia-tara-ofera-sagazduiasca-intalnire-biden-putin-1_607ad65f5163ec4271114df6/index.html",
    "title": "Alte două ţări s-au oferit să găzduiască un viitor summit Biden-Putin",
    "correction": "",
    "type_id": 4,
    "user_id": 1
},
{
    "link": "https://www.romaniatv.net/bilantul-global-al-deceselor-provocate-de-covid-a-depasit-trei-milioane-care-sunt-cele-mai-afectate-tari-din-lume_5426003.html",
    "title": "Bilanțul global al deceselor provocate de COVID a depășit trei milioane. Care sunt cele mai afectate țări din lume",
    "correction": "",
    "type_id": 4,
    "user_id": 1
},
{
    "link": "https://www.digi24.ro/stiri/economie/transporturi/cum-au-ajuns-autostrazile-din-romania-sa-sustina-industrii-din-alte-state-1496723l",
    "title": "Funeraliile prințului Philip. Familia regală și-a luat adio de la „prințul viking”",
    "correction": "",
    "type_id": 3,
    "user_id": 1
},
{
    "link": "https://www.mediafax.ro/social/reteaua-twitter-nefunctionala-la-nivel-global-este-a-doua-oara-in-24-de-ore-cand-site-ul-de-microblogging-intampina-probleme-20045643",
    "title": "Reţeaua Twitter, nefuncţională la nivel global. Este a doua oară în 24 de ore când site-ul de microblogging întâmpină probleme",
    "correction": "",
    "type_id": 3,
    "user_id": 1
},
{
    "link": "https://www.digi24.ro/stiri/economie/bnr-despre-criptomonede-active-speculative-volatile-extrem-de-riscante-furnizorii-de-portofele-digitale-obligati-sa-se-autorizeze-1496599",
    "title": "BNR, despre criptomonede: active speculative, volatile, extrem de riscante. Furnizorii de portofele digitale, obligați să se autorizeze",
    "correction": "",
    "type_id": 3,
    "user_id": 1
},
{
    "link": "https://www.digi24.ro/stiri/economie/transporturi/10-ani-pentru-o-centura-de-7-kilometri-pe-varianta-ocolitoare-a-tecuciului-ar-fi-trebuit-sa-se-circule-inca-de-acum-8-ani-1498153",
    "title": "10 ani pentru o centură de 7 kilometri. Pe varianta ocolitoare a Tecuciului ar fi trebuit să se circule încă de acum 8 ani",
    "correction": "",
    "type_id": 3,
    "user_id": 1
},
{
    "link": "https://www.digi24.ro/stiri/economie/digi-economic/ministerul-finantelor-romania-a-atras-35-miliarde-euro-de-pe-pietele-externe-de-capital-1496505",
    "title": "Ministerul Finanțelor: România a atras 3,5 miliarde euro de pe piețele externe de capital",
    "correction": "",
    "type_id": 3,
    "user_id": 1
},
{
    "link": "https://www.digi24.ro/stiri/economie/digi-economic/strategia-comisiei-europene-pentru-redresare-in-urma-crizei-covid-a-fost-pregatita-o-finantare-de-800-mld-euro-pentru-statele-membre-1495339",
    "title": "Strategia Comisiei Europene pentru redresare în urma crizei COVID. A fost pregătită o finanțare de 800 mld. euro pentru statele membre",
    "correction": "",
    "type_id": 3,
    "user_id": 1
},
{
    "link": "https://www.digi24.ro/stiri/actualitate/aventura-unui-sofer-care-a-aflat-pe-traseu-ca-ii-dispare-drumul-spre-casa-un-element-ciudat-a-aparut-pe-centura-timisoara-sud-1498841",
    "title": "Cio cio",
    "correction": "",
    "type_id": 5,
    "user_id": 1
},
{
    "link": "https://www.digi24.ro/stiri/actualitate/peste-3-milioane-de-oameni-din-intreaga-lume-au-murit-din-cauza-covid-19-care-sunt-cele-mai-afectate-tari-1498947",
    "title": "Aventura unui șofer care a aflat pe traseu că îi dispare drumul spre casă. Un element ciudat a apărut pe centura Timișoara Sud",
    "correction": "",
    "type_id": 5,
    "user_id": 1
},
{
    "link": "https://www.romaniatv.net/familia-regala-pregatita-de-funeraliile-printului-philip-britanicii-isi-iau-adio-de-la-sotul-reginei-elisabeta-a-ii-a-video-live_5425898.html",
    "title": "Regina Elisabeta a II-a își conduce prințul consort pe ultimul drum. Ceremonie restrânsă la Castelul Windsor",
    "correction": "",
    "type_id": 5,
    "user_id": 1
},
{
    "link": "https://www.digi24.ro/stiri/actualitate/guvernul-a-aprobat-proiectul-de-lege-privind-retelele-5g-echipamente-si-soft-doar-de-la-producatori-avizati-de-csat-1496751",
    "title": "Guvernul a aprobat proiectul de lege privind rețelele 5G. Echipamente și soft doar de la producători avizați de CSAT",
    "correction": "",
    "type_id": 5,
    "user_id": 1
},
{
    "link": "https://alephnews.ro/sanatate/bacteriile-rezistente-la-antibiotic-omoara-zeci-de-mii-de-oameni-anual-oms-trage-un-semnal-de-alarma/",
    "title": "Bacteriile rezistente la antibiotic omoară zeci de mii de oameni anual. OMS trage un semnal de alarmă",
    "correction": "",
    "type_id": 5,
    "user_id": 1
},
{
    "link": "https://www.digi24.ro/stiri/sport/fotbal/peste-10-000-de-scaune-de-la-arena-nationala-schimbate-pentru-campionatul-european-de-fotbal-1493193",
    "title": "Peste 10.000 de scaune de la Arena Naţională, schimbate pentru Campionatul European de fotbal",
    "correction": "",
    "type_id": 2,
    "user_id": 1
},
{
    "link": "https://www.mediafax.ro/sport/cfr-cluj-a-castigat-supercupa-romaniei-in-fata-fcsb-la-loviturile-de-departajare-20043531",
    "title": "CFR Cluj a câştigat Supercupa României în faţa FCSB la loviturile de departajare",
    "correction": "",
    "type_id": 2,
    "user_id": 1
},
{
    "link": "https://www.digi24.ro/stiri/sport/alte-sporturi/titi-aur-infectat-cu-covid-pilotul-este-internat-in-spital-1482929",
    "title": "Titi Aur, infectat cu COVID. Pilotul este internat în spital",
    "correction": "",
    "type_id": 2,
    "user_id": 1
},
{
    "link": "https://www.b1.ro/stiri/sport/romania-italia-la-billie-jean-king-cup-s-au-stabilit-meciurile-cine-cu-cine-joaca-in-lipsa-simonei-halep-365401.html",
